name: Test changes
on: [push, pull_request]

jobs:
  test-windows:
    name: Test changes on Windows
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          lfs: true

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.19.4'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install vcpkg & build protobuf lib
        uses: lukka/run-vcpkg@v4
        with:
          vcpkgArguments: 'protobuf:x64-windows-static'
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'

      - name: Move protobuf lib into vendors dir
        run: copy ${{ github.workspace }}/vcpkg/installed/x64-windows-static/lib vendors/protobuf/lib

      - name: Build
        shell: cmd
        run: |
          mkdir build
          pushd build
          cmake -G"Visual Studio 16" -A x64 ..
          cmake --build . --config Release

  test-linux:
    name: Test changes on Linux
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          lfs: true

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.19.4'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install gcc-8 g++-8
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-8 ..
          cmake --build . --config Release